name: Build and Deploy Test

on:
  push:
    branches: [test]

jobs:
  deploy-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: clean cache
        run: yarn cache clean

      - name: Install
        run: yarn install
        
      - name: Install plugin deps
        run: yarn install-plugins-deps
        
      - name: Build
        run: yarn build
        env:
          CI: false
          NODE_ENV: 'production'

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'test-daospace.starcoin.org'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          SOURCE_DIR: 'build'
