name: Build and Test

on:
  pull_request:
    branches: [ 'main', 'test', 'release-**' ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: clean cache
      run: yarn cache clean

    - name: Install
      run: yarn install
      
    - name: Build
      run: yarn build
      env:
        CI: false
        NODE_ENV: 'production'
